### PR TITLE
First draft of style guide

### PR DESCRIPTION
**Pull request by sselin-co**

### CODE REVIEW

**Review by shepkeira — APPROVED** [review]
I have no sense of style/aesthetic but the style guide part is clear 👍

**Comment by sayo96825** [comment]
image

I am getting something like this snip. Is this correct?

**Comment by shepkeira** [comment]
> image
> 
> I am getting something like this snip. Is this correct?

It should show a list of HEX colour codes, and a font (and I think a few other things). Should look like a regular text file.
It's a pdf so github won't load it correctly. You'll have to download the file to view it. That's likely where this error is coming from

**Review by sayo96825 — APPROVED** [review]
Thank you!
I can see it now.

**Pull request merged**
