### PR TITLE
Dynamic navbar + misc. style changes

### PR DESCRIPTION
**Pull request by sselin-co**
I tried to get the client facing links to only show in the navbar when a client is logged in but it isn't working quite yet. At the moment, it correctly hides the login/signup buttons when authenticated and shows a link to the admin UI when logged in as a superuser such as 'root'.

### CODE REVIEW

**Comment by Rock-it-science** [comment]
Nice, looks like everything works for me, although I'm curious is this meant to be there:
image

**Comment by sselin-co** [comment]
I just pushed a small commit to fix that! Forgot I left it in there for testing 🤷‍♂️

**Review by Rock-it-science — APPROVED** [review]

**Review by sayo96825 — APPROVED** [review]
Looks good!

**Review by shepkeira — APPROVED** [review]
Looks good 👍

**Pull request merged**
