### PR TITLE
Database backup script

### LINKED ISSUE #60: Docker Back Up Script
- Create a script that does the docker backup stuff for us

### PR DESCRIPTION
**Pull request by Rock-it-science**
Changes work for me on Linux, but I have a sinking feeling the container name isn't going to work on Windows.
Its worth a shot though because the workaround may be complicated :thinking: 
closes #60

### CODE REVIEW

**Review by sayo96825 — COMMENTED** [review]
I get error as discussed in the meeting.
The container name did not get changed again.

**Comment by Rock-it-science** [comment]
I looked into modifying the script so that it runs in the container, and unfortunately due to the fact that the container is not aware of its host, it is not possible to copy the backup file out of the container if the script is running in the container.

So this is probably the best we can reasonably get. I have included steps in the readme that details how you could either use the script or the commands to create, and copy the backup file to the host, we will just have to remember that the container name may have to be changed for certain machines.

**Comment by Rock-it-science** [comment]
Oh yeah, I also added a force flag to the remove command so the script should not halt if there is an error caused by the file not existing. It will still output a warning, but the script should continue running as expected.

**Review by shepkeira — APPROVED** [review]
This works for me!

**Review by sayo96825 — DISMISSED** [review]
It worked for me !

**Comment by sselin-co** [comment]
Does anyone know why I might get this error when running the script? `Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user 'SA'..` I was able to get the script to run after turning the shell script into a bash script for Windows compatibility but this seems to keep throwing me.

**Comment by sselin-co** [comment]
I added a commit with a backup file that works on windows. You don't have to try it since it won't work on non windows machines.

**Review by sselin-co — APPROVED** [review]

**Pull request merged**
