### PR TITLE
Moved client links from homepage into base html navbar

### PR DESCRIPTION
**Pull request by sselin-co**
Set up tags to check if a user is not staff or is not anonymous (not logged in) to determine if the client links need to be shown.

To make this more robust, we need to implement authentication groups for clients, lab workers, and lab admins that can have unique permissions associated with them.

### CODE REVIEW

**Comment by Rock-it-science** [comment]
It looks like the client links still appear if the user is an employee.
I believe we do have different groups for employees and clients already. It might make more sense to write a view function than doing this all in the template.

**Review by shepkeira — CHANGES_REQUESTED** [review]
Works for the super user (root), and client!
However logging in as a lab worker shows the client nav bar

**Comment by sselin-co** [comment]
Turns out the problem was I hadn't backed up the database so you guys never got the build with the correct group assignments. I'm working on a commit now to rectify the issue

**Comment by sselin-co** [comment]
Hmm did not realize there would be a branch conflict, fixing

**Pull request merged**
