### PR TITLE
Analysis page

### PR DESCRIPTION
**Pull request by shepkeira**
- Able to create test_samples from the lab_sample page (also creates a received test result)
- Able to update sample information from the sample page
- Able to view analysis page with a list of all labs
- Able to view each labs list of samples ready for analysis (lab samples without test samples)
- Able to access test results from the test_sample page
- Able to update the results

### CODE REVIEW

**Review by Rock-it-science — CHANGES_REQUESTED** [review]
Everything looks really good! This update really makes things come together and makes it feel like a complete system from the employees' perspective.
Just a couple tiny things I mentioned in comments.
Also, when I put in results for a sample test, where does that show up? I don't see it on the Test Sample page.

**Comment by Rock-it-science** [comment]
Also maybe some time we can ditch the "welcome to X page" some time, I think its kind of unnecessary now that the pages are populated with content.

**Comment by shepkeira** [comment]
> Everything looks really good! This update really makes things come together and makes it feel like a complete system from the employees' perspective. Just a couple tiny things I mentioned in comments. Also, when I put in results for a sample test, where does that show up? I don't see it on the Test Sample page.

You should see the results if you go from the test sample page and follow the link to the test sample analysis page, from there you can see the current results or update results

**Comment by shepkeira** [comment]
> Also maybe we can ditch the "welcome to X page" some time, I think it might be unnecessary now that the pages are populated with content.

We can address this while Sayo works on the UI fixes since it's in a lot of places.

**Comment by Rock-it-science** [comment]
> > Everything looks really good! This update really makes things come together and makes it feel like a complete system from the employees' perspective. Just a couple tiny things I mentioned in comments. Also, when I put in results for a sample test, where does that show up? I don't see it on the Test Sample page.
> 
> You should see the results if you go from the test sample page and follow the link to the test sample analysis page, from there you can see the current results or update results

Okay nice I see it now. For some reason it wasn't working for me before

**Review by Rock-it-science — APPROVED** [review]

**Pull request merged**
