### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by shepkeira**
- Liniting all the code
- Make everything look nice
- Make sure we have comments everywhere!

### CODE REVIEW

**Comment by shepkeira** [comment]
PLEASE test thoroughly before approving! A lot of things were changed

**Comment by Rock-it-science** [comment]
Currently getting this error when trying to access order results for the The Brain. I hadn't modified any orders from the default so it should be reproducible. I think this might have been fixed in another branch but I can't remember.
image

**Comment by shepkeira** [comment]
> Currently getting this error when trying to access order results for the The Brain. I hadn't modified any orders from the default so it should be reproducible. I think this might have been fixed in another branch but I can't remember. image

fixed

**Comment by Rock-it-science** [comment]
Clicking on a sample I am getting this error:
image

**Comment by Rock-it-science** [comment]
Same error is failing unit tests. Good news is everything else appears to still work 🤞 
image

**Comment by shepkeira** [comment]
I'm unable to replicate this error. Is anyone else able to replicate it?

**Comment by sselin-co** [comment]
@shepkeira, what linter are you using? That way I can set the right one in VS Code

**Comment by sselin-co** [comment]
I'm having no issues, everything appears to be working correctly. All the pages are accessible and the tests all succeeded. @Rock-it-science, have you tried nuking your container and rebuilding? I used `docker system prune --all --volumes` to fix the crispy forms installation issue I was having a couple days ago.

**Comment by shepkeira** [comment]
> @shepkeira, what linter are you using? That way I can set the right one in VS Code

I used pylint (I think I noted it in the readme) there are a few errors left because of the way django works it thinks there are errors in our code lol (like it doesn't think any of our models should have ids because they aren't explicitly defined so when we reference them, it throws an error)

**Comment by shepkeira** [comment]
> Clicking on a sample I am getting this error: image

The issue was that the static/barcodes folder wasn't persisting because it was empty. So when the repo got recloned, it didn't have that folder. Solved in the latest commit, where we add a .gitkeep to the folder so it persists

**Review by Rock-it-science — APPROVED** [review]
Looks good!

**Pull request merged**
