### PR TITLE
Final Merge to Main

### PR DESCRIPTION
**Pull request by shepkeira**

### CODE REVIEW

**Comment by sselin-co** [comment]
I'm running as a clean a build of this as I can to make sure there are no issues. Should we make a release out of this? Like a 1.0 or something

**Comment by shepkeira** [comment]
> 

I don't think it's really at 1.0 capacity. It's not really like releasable in its current capacity, you know?

**Comment by sselin-co** [comment]
I agree, if we're gonna do a release then it needs to be 0.1 alpha

**Comment by shepkeira** [comment]
0.0.1 alpha (minor fix, now it exists lol)
I think 0.1 alpha is correct. Like ready for testing and development, still gonna need a fair amount of work to be something decent to like show to a user lol
Pre-relase naming convention agrees with us! (https://www.drupal.org/docs/develop/git/git-for-drupal-project-maintainers/release-naming-conventions#pre-release)

**Comment by sselin-co** [comment]
I noticed a spelling error on the order history page. Should I open a PR real quick to fix that?

**Comment by sselin-co** [comment]
No idea lol, but I can also confirm that email now works on my end

**Comment by shepkeira** [comment]
I just checked and its been there since the page was made. Like two peer testings, and multiple checks of that page ahaha

**Review by sselin-co — APPROVED** [review]
Everything looks good to me 👍

**Review by sayo96825 — APPROVED** [review]
Looks good to me !!
Thank you for fixing that spelling mistake.

**Review by Rock-it-science — APPROVED** [review]
Yup all looks good to me too! 🥳

**Comment by sselin-co** [comment]
The (almost) end of an era. It was a pleasure working with you guys!

**Pull request merged**
