### PR TITLE
Customer Home Page, Employee Home Page

### PR DESCRIPTION
**Pull request by shepkeira**
- Adding customer home page
- Redirect Customer Login to Customer Home Page
- Adding Employee home page
- Redirect Employee Login to Employee Home Page
- Adding blank pages to redirect to for customer home child pages

### CODE REVIEW

**Comment by sselin-co** [comment]
Looks good to me! I like how the homepage adjusts based on if a user is staff or not instead of having separate logins entirely.

**Review by sselin-co — APPROVED** [review]

**Review by sayo96825 — COMMENTED** [review]
image

I keep getting this error. I appreciate any suggestion.
After I fixed docker issue everything was fine, but I deleted all the path in environment variable  by accident. I think I put all the path back and my django and docker tutorial is running fine.

**Comment by shepkeira** [comment]
> image
> 
> I keep getting this error. I appreciate any suggestion. After I fixed docker issue everything was fine, but I deleted all the path in environment variable by accident. I think I put all the path back and my django and docker tutorial is running fine.

Are you getting this error on other branches? Try running development, and that you are using the docker container to run the app

**Review by sayo96825 — APPROVED** [review]
It is working !!
There was also something wrong with powershell.exe. 
Thank you so much 🙇‍♀️

**Review by Rock-it-science — APPROVED** [review]
Amazing! It finally feels like we have something going now lol
Looks like everything works for me

**Pull request merged**
